### ISSUE TITLE
XBEE-RX: Not receiving data ...

### ISSUE THREAD

**Issue by MKoroschetz** [ramonmata/node-red-contrib-xbee#3]
I am successfully using the XBEE-TX node to communicate from node-red running on a rPi-3B+ (and 2B). My modules, xbee-zb series 2, use frame types "0x17 Remote Command Request", and "0x10 ZigBee Transmit Request" for sending commands to the remote nodes. I am using mode API=1. Transmit is working perfectly and all devices responde consistently and reliably to the commands.

However, I have been unable to get the XBEE-RX node to work. For simplicity I have the output of the XBEE-RX connected directly to a debug node, which never gets any messages. When I look at the transissions happening using Digi's XCTU I see the proper and expected responses from the devices, but these never show up in the debug node. I am expecting (and seeing in XCTU) frame types "0x90: ZigBee Receive Packet" and "0x92: ZigBee IO Data Sample Rx Indicator".

My node-red execution environment is a docker-compose image.

- Occasionally I get an error with the message"Error occurred, see console for details". I have not been able to understand how to capture / look at the corresponding message on the console. In any case I know which transmit packet triggers the error

- I do not see any obvious configuration parameters in the node configuration that could have an impact on the issue.

Any help for troubleshooting this issue further or any hint for a solution is greatly appreciated.

**Comment by ramonmata** [comment]
Hi MKoroschetz, 

"Error occurred, see console for details", the error message is printed at the terminal console of your Raspberry OS. When this happens, try opening a terminal session in the Raspberry and execute the following command:

`pi@host> node-red-log`

to see the logging messages

Other than that, not sure why your setup is failing.


best regards!
