### ISSUE TITLE
Extract Sensor data

### ISSUE THREAD

**Issue by MartinSokolov15** [ramonmata/node-red-contrib-xbee#6]
Hi, i use XBee module with board, that use breadboard, on which we can attach simple sensors. I use this nodehttps://flows.nodered.org/node/node-red-contrib-xbee , to ''listening'' for data and  I tried to extract sensor data via xbee api node and function node with msg.payload, but in the debug node  i don't receive anythin. Any help?

**Comment by ramonmata** [comment]
It could be many things, here are 2 that I think could help:
- Make sure your XBees network is configured correctly for each Xbee
- Check the connections between your XBee and GPIO on your Raspberry

best regards!

**Comment by martin9115** [comment]
I checked the connections via XCTU software
I don't use RPI i connect it directly to PC

**Comment by ramonmata** [comment]
Ok, let's try this, with XCTU should be able to debug that XBees are
reading and transmiting sensor data.

Could you try this? If all of this looks correct, then it may be a
configuration thing to check with the NodeRed nodes, specifically the
configuration nodes where you specify the COM port, etc for the RX and TX
nodes.

Also you may need to send a command to the XBee to enable reading the
sensor, or it can be configured to make it automatically. But with the XCTU
you may check that.

Best regards!

**Comment by ramonmata** [comment]
Also, **Node-RED** has a very useful command to debug what's happening within the flow
Try the `node-red-log` command line utility (_should included in your Node-RED installation_) and look for any error messages.

There are more logging options in this link that may help to understand what's happening in Node-RED: https://nodered.org/docs/user-guide/runtime/logging

Best regards!

**Comment by ramonmata** [comment]
Closing for now, feel free to reopen if you find an issue with the library

best regards!

**Comment by martin9115** [comment]
I try this, but in the video not all configs are visible, so i could't repeat them. Can anyone please help me?
https://www.youtube.com/watch?v=K-jov9Cvxcw&t=46s

**Comment by martin9115** [comment]
Hi, i try this example, but i can't see the message ''Hello'', that supposed to come up and i've got this in the debug node.
Where can be my mistake?

![107935345-f1a11300-6f89-11eb-8a1d-62609c6c066b](https://user-images.githubusercontent.com/50946705/125917229-d61d7781-ffdd-4747-a218-f9afaeb74952.jpeg)
![107935357-f6fe5d80-6f89-11eb-84ae-0d11e0da767b](https://user-images.githubusercontent.com/50946705/125917260-05578f67-bca8-467a-b308-6f22e3cbc0d9.jpeg)

![107935378-fcf43e80-6f89-11eb-9abd-5a141081610f](https://user-images.githubusercontent.com/50946705/125917282-a881e39f-8371-437b-93f7-b9edc5d98e42.jpeg)

![114191291-ec8e8d80-9954-11eb-9de8-19101f112aef](https://user-images.githubusercontent.com/50946705/125917306-943dd667-b4ca-4187-8515-44aaf2ef8ad2.jpg)
